### ISSUE TITLE
Not pulling in latest crystal-lang/db library?

### ISSUE THREAD

**Issue by zachad** [crystal-lang/crystal-mysql#2]
I'm having a problem using crystal-mysql:

> Error in ./libs/db/db/result_set.cr:60: abstract `def DB::ResultSet#column_type(index : Int32)` must be implemented by MySql::ResultSet

It seems that the abstract DB::ResultSet has been removed from the latest version of crystal-lang/db however, when I install this via the shard.yml and `crystal deps` it is pulling an out of date version of the `db` code.

Is this an issue with shard or with the specific version requirement in crystal-mysql's shard.yml file?

This is the same exact issue that is causing TravisCI to report that the [BuildFailed](https://travis-ci.org/crystal-lang/crystal-mysql)

**Comment by bcardiff** [comment]
Hi @zachad, some little fixes were missing.
Your current options are:

  1. Add `version: ~> 0.1.1` on your shard.yml when referencing crystal-mysql
  2. Add `branch: master` on your shard.yml when referencing crystal-mysql

`branch: master` will use crystal-db master branch which you can think of as unstable.

The tag v0.1.0 was missing in crystal-mysql.
The shard.yml in crystal-mysql master was fixed to reference crystal-db master branch.
And travis have been failing to due certificates issues so I missed the real upgrade to latest crystal version issue (actually I think it is a regression bug crystal-lang/crystal#2957)
I've release v0.1.1 with the fix for latest crystal version.

Reopen/comment if there are still some issues.
Thanks!

**Comment by zachad** [comment]
Thank you!

I chose to do `version: ~> 0.1.1` and things look good as far as compilation goes. Getting an `Index out of bounds (IndexError) at runtime, but that's another story. I'll try and chase that down now.
